# Github Actions 下载脚本配置
version: '2.0'

dir_rule:
  base_dir: D:\Documents\Workspace\JmPlugin\data
  rule: Bd_Aid

# client:
#   domain:
#     - 18comic.vip
#     - 18comic.org

download:
  cache: true # 如果要下载的文件在磁盘上已存在，不用再下一遍了吧？
  image:
    decode: true # JM的原图是混淆过的，要不要还原？
    suffix: .jpg # 把图片都转为.jpg格式
  threading:
    # batch_count: 章节的批量下载图片线程数
    # 数值大，下得快，配置要求高，对禁漫压力大
    # 数值小，下得慢，配置要求低，对禁漫压力小
    # PS: 禁漫网页一般是一次请求50张图
    batch_count: 45

# plugins:
#   after_album:
#     # 把章节的所有图片合并为一个pdf的插件
#     # 使用前需要安装依赖库: [pip install img2pdf]
#     - plugin: img2pdf
#       kwargs:
#         pdf_dir: D:\Documents\Workspace\JmPlugin\data # pdf存放文件夹
#         filename_rule: Pid # pdf命名规则，P代表photo, id代表使用photo.id也就是章节id